### ISSUE TITLE
Permission Denial: opening provider ... from ProcessRecord{...} requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

### ISSUE THREAD

**Issue by afilp** [RonRadtke/react-native-blob-util#118]
```
    env: Android
    "react-native": "0.66.2",
    "react-native-blob-util": "^0.14.0",
```

I get the following error when trying to copy a video in order to upload it, using the new `copyToInternal" function:

```
          await ReactNativeBlobUtil.MediaCollection.copyToInternal(
            el.uri, // content uri of the entry in the media storage
            destpath, // path to destination the entry should be copied to
          )
```

The error is this:
```
Fatal Exception: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{b94f6fd 12170:com.myapp.viewer/u0a658} (pid=12170, uid=10658) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
       at android.os.Parcel.createException(Parcel.java:2360)
       at android.os.Parcel.readException(Parcel.java:2343)
       at android.os.Parcel.readException(Parcel.java:2285)
       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5933)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:7185)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2954)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2509)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1994)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1825)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1502)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtilMediaCollection.copyToInternal(ReactNativeBlobUtilMediaCollection.java:84)
       at com.ReactNativeBlobUtil.ReactNativeBlobUtil.copyToInternal(ReactNativeBlobUtil.java:4)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:147)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loop(Looper.java:236)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:923)
```
```
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7505)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7969)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2486)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2981)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
```

### How?

I select a video with "react-native-image-picker".

I store its reference in *AsyncStorage*, for future uploading (the user may select photos/videos but close the app and re-open it later in order to upload the files):

```
    /*
    * Example of picked asset (video) in Android, saved in AsyncStorage to be retrieved later:
    *
      {
        "height": 320,
        "width": 568,
        "type": "video/mp4",
        "duration": 9,
        "fileName": "video:45544",
        "bitrate": 465939,
        "fileSize": 566583,
        "uri": "content://com.android.providers.media.documents/document/video%3A45544"
      }
    *
    * */
```

I re-open the app later, I do see the video's thumbnail in the UI (retrieved from AsyncStorage):
![image](https://user-images.githubusercontent.com/7850073/153743965-f07cdac6-1087-4a53-816e-33db49802c4b.png)

I start uploading.

When it goes to upload the video (photos work OK), the app crashes with above error.

This has to do something with the new `"uri": "content://` logic.

1. Is there something I can do to prevent this error?
2. Is there a method (like "exists") to be used also with `content://` uris? I suspect that maybe the actual file is not in the cache anymore (don't know why).

Thanks a lot!

**Comment by afilp** [comment]
UPDATE: 
I cannot even `try/catch` the error, the app crashes
```
try {
            await ReactNativeBlobUtil.MediaCollection.copyToInternal(
              el.uri, // content uri of the entry in the media storage
              destpath, // path to destination the entry should be copied to
            );
            console.log('OLD el.uri', el.uri);
            el.uri = destpath;
          } catch (e) {
            Alert.alert(e);
          }
```

**Comment by RonRadtke** [comment]
The content-uri can change. What a content uri is, is basically a type of pointer, so it's not the physical address on the harddrive but just a pointer for a database-row. And this pointer can change.
So it is in general not stable to store the URI for a later usage, simply because there is no guarantee for the URI still being valid. It is only as long valid as the cursor object, which was used to get the URI, is alive. Everything else is luck.

The error has to be caught in the native part of the library. So that's something I have to fix.

But for your part, you can't relay on the content URI from a previous session. Either you copy the file directly or the user has to select it again..
Please try if it works if you copy the video directly.

**Comment by afilp** [comment]
I copied it immediately after picking the video, here is the code, and I changed the `uri` to the new `destPath` (I added the `file:///` too), so now I store this object instead:
```
[
  {
    "height": 1080,
    "width": 1920,
    "type": "video/mp4",
    "duration": 30,
    "fileName": "msf:50",
    "bitrate": 4675011,
    "fileSize": 17839845,
    "uri": "file:///data/user/0/com.doorfeed.viewer.debug/cache/2022-02-13-16-09-43-947.mp4"
  }
]
```

And seems to be working! 

So the idea is to copy ASAP (through your new `MediaCollection` code) the file, after picking it, into the `cache` folder of the app. Thanks!

One small detail though, I could never see any file inside the `cache` folder of the app, while I am pretty sure they are there:

![image](https://user-images.githubusercontent.com/7850073/153758137-49194887-27b8-43d6-b1b0-c8d67060fdf6.png)

I used the `Total Commader` app, I used `files` app, all show the same: No files in `cache` folder (neither in `files`).

**Comment by RonRadtke** [comment]
> 1. How can I solve the "re-granting the permission" issue? Is it solvable?

Nope, it's not since it is due to the nature of the permission.



> 2\. I assume trying to copy the file directly should be only for Android, correct? Regardless of Android version?

Not necessarily. On very old devices you might not need it. You might want to try it. I honestly forgot to test the copy functionality with < Android 10.

Yep, you never will see any there. At least not on Android 11. Simply because total commander does not have the possibility to see these files anymore. We got restrictions, that Apps are not allowed to see files within another apps private storage anymore.

**Comment by RonRadtke** [comment]
Can we close the issue? @afilp

**Comment by afilp** [comment]
Yes, thanks a lot!
