### ISSUE TITLE
[Android only] Error when fetching PDF from URL "Use of own trust manager but none defined"

### ISSUE THREAD

**Issue by epshtielsl** [RonRadtke/react-native-blob-util#152]
**please provide the version of installed library and RN project.**
"react-native": "0.67.2",
"react-native-blob-util": "^0.16.0",
"react-native-pdf": "^6.5.0",

**a sample code snippet/repository is very helpful to spotting the problem.**

```
import PDF from 'react-native-pdf'

...

<PDF
   source={{ uri: TERMS_URL, cache: true }}
   style={styles.pdf}
   onError={(error) => console.log(error)}
/>

...

```

Error logs
```
2022-05-04 11:44:25.952 13280-13354/com.veecon W/System.err: java.lang.RuntimeException: java.lang.IllegalStateException: Use of own trust manager but none defined
2022-05-04 11:44:25.953 13280-13354/com.veecon W/System.err:     at com.ReactNativeBlobUtil.ReactNativeBlobUtilUtils.getUnsafeOkHttpClient(ReactNativeBlobUtilUtils.java:86)
2022-05-04 11:44:25.953 13280-13354/com.veecon W/System.err:     at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq.run(ReactNativeBlobUtilReq.java:319)
2022-05-04 11:44:25.953 13280-13354/com.veecon W/System.err:     at com.ReactNativeBlobUtil.ReactNativeBlobUtil.fetchBlob(ReactNativeBlobUtil.java:366)
2022-05-04 11:44:25.953 13280-13354/com.veecon W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at java.lang.Thread.run(Thread.java:920)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err: Caused by: java.lang.IllegalStateException: Use of own trust manager but none defined
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err:     at com.ReactNativeBlobUtil.ReactNativeBlobUtilUtils.getUnsafeOkHttpClient(ReactNativeBlobUtilUtils.java:65)
2022-05-04 11:44:25.954 13280-13354/com.veecon W/System.err: 	... 13 more
```

**Comment by epshtielsl** [comment]
Issue had to do with the `trusty` flag
