### ISSUE TITLE
TypeError: Cannot read property 'getConstants' of null,

### ISSUE THREAD

**Issue by dekunleroy** [RonRadtke/react-native-blob-util#204]
Hi, I am trying to convert an image url prefixed with https:// into base64 string using the **react-native-blob-util**, however I got this error after installing and also doing a pod install

- react-native-blob-util Version: 0.17.0
- RN Version: 0.70.4

         const handleShare = async () => {
           const meetupImageUrl = getImageUrl(meetup.cover_photo, ImageVariant.preview);
           await ReactNativeBlobUtil.fetch('GET', meetupImageUrl)
              .then((res) => { 
               let status = res.info().status;
                if (status == 200) {
                    // the conversion is done in native code
                    let base64Str = res.base64();
                    console.log('base64Str', base64Str);
                }
                else {
                    // handle other status codes
                }
            })
            // Something went wrong:
            .catch((errorMessage, statusCode) => {
                // error handling
            });
        console.log('meetupImageUrl', meetupImageUrl)
       };

**Comment by RonRadtke** [comment]
Did you install the package (and link) and rebuild the app and cleaned build caches first if needed?
Sounds like it didn't load the lib correctly.

**Comment by dekunleroy** [comment]
> Did you install the package (and link) and rebuild the app and cleaned build caches first if needed?
> Sounds like it didn't load the lib correctly.

Yes I took this exact steps

**Comment by SheetJSDev** [comment]
To reproduce:

```bash
npx react-native init RNBU204 --version="0.70.6"
cd RNBU204
npm i --save react-native-blob-util
echo "import RNFetchBlob from 'react-native-blob-util';" >> App.js 
npm run ios
```

The Metro window shows the following errors:

```
 ERROR  TypeError: Cannot read property 'getConstants' of null, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

For iOS, the "fix" is to run `pod install` from the `ios` folder and rebuild the app.  To see that in action, close Metro and run:

```bash
cd ios; pod install; cd ..
npm run ios
```

This probably should be documented somewhere, since the current documentation strongly suggests `npm install` suffices when working with RN 0.70 ("manual linking should not be required" and the actual `react-native link` command was removed)

**Comment by dekunleroy** [comment]
@SheetJSDev I'm going to try out your suggestions. Although I no longer need this package as I found another solution

**Comment by RGLxAkuma** [comment]
> @SheetJSDev I'm going to try out your suggestions. Although I no longer need this package as I found another solution

What solution you found as I am getting the exact error when I tried this package

**Comment by SheetJSDev** [comment]
For iOS, the "fix" is to run `pod install` from the `ios` folder and rebuild the app:

```bash
cd ios; pod install; cd ..
npm run ios
```

**Comment by RGLxAkuma** [comment]
> For iOS, the "fix" is to run `pod install` from the `ios` folder and rebuild the app:
> 
> ```shell
> cd ios; pod install; cd ..
> npm run ios
> ```

For android??

**Comment by SheetJSDev** [comment]
Our React Native + RNBU demo (https://docs.sheetjs.com/docs/demos/mobile/reactnative#demo select "RNBU" in step 4) builds and runs in the simulator for Android 12 (S) Platform 31 Pixel 5.  This works in RN 0.70.6 + RNBU 0.17.1 and in RN 0.70.4 + RN 0.17.0 (the versions used by @dekunleroy).

Can you test if the same issue shows up in a new project?  Try:

```bash
npx react-native init RNBU204 --version="0.70.4"
cd RNBU204
npm i --save react-native-blob-util@0.17.0
echo "import RNFetchBlob from 'react-native-blob-util';" >> App.js 
npm run android
```

**Comment by SheetJSDev** [comment]
Issue can be reproduced in Expo Snack (both iOS and Android).  https://github.com/expo/snack/issues/385 tracking issue.

**Comment by RonRadtke** [comment]
> Issue can be reproduced in Expo Snack (both iOS and Android). [expo/snack#385](https://github.com/expo/snack/issues/385) tracking issue.

Yeah but this is expo. I'm using native code and as far as I know am not part of the Expo SDK... So it won' work.

**Comment by SheetJSDev** [comment]
Expo Snack issue was raised when trying to make [our react native demo](https://docs.sheetjs.com/docs/demos/mobile/reactnative/#demo) work with the snack.  It happened to have the same message but 

This issue is reproducible locally on iOS using the first snippet from an up-thread comment https://github.com/RonRadtke/react-native-blob-util/issues/204#issuecomment-1374646366 :

```bash
npx react-native init RNBU204 --version="0.70.6"
cd RNBU204
npm i --save react-native-blob-util
echo "import RNFetchBlob from 'react-native-blob-util';" >> App.js 
npm run ios
```

Tested on iPhone 14 (iOS 16.2), the error is

```
 ERROR  TypeError: Cannot read property 'getConstants' of null, js engine: hermes
```

The project issue is resolved by running `pod install` from the `ios` directory and rebuilding:

```bash
cd ios; pod install; cd ..
npm run ios
```

It's hard to tell if this is a bug in RNBU or merely an oversight in the docs.  The Installation section of the docs does not mention the `pod install` step.

**Comment by RonRadtke** [comment]
I would add the pod install to the docs. It makes sense that a pod install might be required.
But we had some issues on ios side too: https://github.com/RonRadtke/react-native-blob-util/pull/219

**Comment by SoyDiego** [comment]
Same issue here when I'm trying to start the APP.
Any solution?

Thanks

**Comment by Jheysson** [comment]
Same issue

**Comment by babarbahadur** [comment]
I tried adding mock code into setup file.

`jest.mock('react-native-blob-util', () => { return { DocumentDir: () => {}, polyfill: () => {}, }; });
`
Also downgraded the library to version 0.17.0 but still facing the same issue :(

```
TypeError: Cannot read properties of null (reading 'getConstants')

 at Object.<anonymous> (node_modules/react-native-blob-util/fs.js:14:39)
 at Object.<anonymous> (node_modules/react-native-blob-util/index.js:8:1)
```

**Comment by sungsong88** [comment]
I have the same issue with Android. Any solutions? `instrument.js cannot read property getConstants of null`

**Comment by atologistdipak** [comment]
same issue

**Comment by raldred** [comment]
I sorted this by creating when running tests with jest by creating a manual mock
`__mocks__/react-native-blob-util.js`
containing simply:
```js
export default jest.fn();

```

Which covered off tests which weren't actually touching react-native-blob-util.
For tests of modules which did use react-native-blob-util, i mocked as follows:


```js
jest.mock("react-native-blob-util", () => ({
  android: {
    actionViewIntent: jest.fn(),
  },
  ios: {
    openDocument: jest.fn(),
    previewDocument: jest.fn(),
  },
  config: jest.fn(),
  fs: {
    dirs: {
      DocumentDir: "yourdocumentdir",
      DownloadDir: "yourdownloadsdir",
    },
  },
}));
```

**Comment by Balthazar33** [comment]
> if you face this issue when trying to test your code , put this code in setup file :
> 
> `jest.mock('react-native-blob-util', () => { return { DocumentDir: () => {}, polyfill: () => {}, }; });`

The following worked for me:
```
jest.mock('react-native-blob-util', () => {
  return {getConstants: () => {}, polyfill: () => {}};
});
```

P.S. I faced this error only while running jest.

**Comment by Milanjiji** [comment]
worked for me!

it was the issue of the version
i was using `0.19.6` which was released about 2 weeks which was the problem 
i degraded the `react-native-blob-util` to  version `0.19.5` and is working fine now.

**Comment by buyi-web** [comment]
Same issue with Android

**Comment by zdsantos** [comment]
Same here

**Comment by tiagopazhs** [comment]
Same here

**Comment by m-sterspace** [comment]
In my case, I got these errors trying to use this with Expo Go, instead, you have to use an Expo Development build. You can create a dev build, sideload it onto your emulator / test device, and have it grab the latest js bundle automatically (just like expo go), by running `npx expo run:android`

**Comment by kirtikapadiya** [comment]
> worked for me!
> 
> it was the issue of the version i was using `0.19.6` which was released about 2 weeks which was the problem i degraded the `react-native-blob-util` to version `0.19.5` and is working fine now.

not working with expo SDK 49 with expo go.

**Comment by m-sterspace** [comment]
> > worked for me!
> > 
> > it was the issue of the version i was using `0.19.6` which was released about 2 weeks which was the problem i degraded the `react-native-blob-util` to version `0.19.5` and is working fine now.
> 
> not working with expo SDK 49 with expo go.

It will not work with Expo Go, you need to use Expo Development Builds.

**Comment by Favot** [comment]
> jest.mock('react-native-blob-util', () => {
>   return {getConstants: () => {}, polyfill: () => {}};
> });

You can put this in the `jest.config.js` file, or create a specific file for it like `__mocks__/react-native-blob-util.ts` 

Then update your `jest.config.js` as :

```
module.exports = {
  ...
    setupFilesAfterEnv: [
       ...
        './__mocks__/react-native-blob-util.ts',
    ],
};
```

**Comment by WaheedRumaneh** [comment]
> > if you face this issue when trying to test your code , put this code in setup file :
> > `jest.mock('react-native-blob-util', () => { return { DocumentDir: () => {}, polyfill: () => {}, }; });`
> 
> what do file do i put this information at ?

the `setup file` or you also can call it `mock file`, it's a custom file that you will create once set up a project, this file will be linked with `jest.config.js` and will contain all general packages mocks or any general test functions that you want to apply them on all test cases that you have within the project,

hope this could help you.

**Comment by mMarcos208** [comment]
Same issue on Android.
Any solution?

"react-native-blob-util": "0.19.4" and "react-native": "0.72.10",

**Comment by Rahmathirshad** [comment]
> if you face this issue when trying to test your code , put this code in `setup file` :
> 
> `jest.mock('react-native-blob-util', () => { return { DocumentDir: () => {}, polyfill: () => {}, }; });`
> 
> if you don't have the `setup file` you can add it like this:
> 
> * create a new file `setup/setup.test.ts` inside your `__test__` directory
> * link it with `jest.config.js` by adding this code `  setupFiles: ['<rootDir>/__tests__/setup/setup.test.ts'], testPathIgnorePatterns: [ '<rootDir>/__tests__/setup', ... ],`
>   
>   * stop the metro if it was running and re-run the app again
> 
> now you can add any general mock like i mentioned at the beginning or test functions inside it to be applied on all your test cases.

I'm using expo, getting same error " TypeError: Cannot read property 'getConstants' of null, js engine: hermes ",...
I tried to follow steeps as above mentioned but I couldn't find "setup file", even tried to create as you said but there is no  `__test__` directory in my project....... what to do next please help

**Comment by MahdiAsadifard** [comment]
Same issue on Android development build. Any solution?
"react-native-blob-util": "^0.19.9"
"react-native": "0.74.2"
"expo": "^51.0.9"

**Comment by Anurodhydv** [comment]
can anyone please provide the accurate solution to this ? react-native-blob-util is giving this error

**Comment by cheprasov-dev** [comment]
Same here

**Comment by phazei** [comment]
I am NOT using Expo. I'm also getting this issue, just straight react native.

I got it working on iOS.  We have a NX mono-repo.  Unlike all our other packages, something is weird with this one in that it doesn't detect that it needs to add `"react-native-blob-util": "*"` to the react-native package.json after we add `"react-native-blob-util": "^0.21.2",` to the project package.json, although it did detect and add `react-native-cache-video` just fine which has this blob util as a dep which has led us here.  After adding that a `pod install` added it and got it working on iOS.

Android OTOH, usually doesn't need anything else, I rebuilt and it didn't work.  Then I reinstalled all npm packages, I did a `gradle clean` and actually... I think it's working now.  Maybe this comment will help someone in the future.

I was about to try this since Claude had suggested something similar right before it started working:
https://github.com/RonRadtke/react-native-blob-util/issues/238#issuecomment-1497998815
I wanted to connect that solution here since it's harder to find.

**Comment by kevin-roan** [comment]
If you disable the new architecture, this will work just fine. i haven't found a way to fix this issue but alternative libraries can be helpful.

**Comment by Ali-Aref** [comment]
any updates? I am still getting this issue

**Comment by sridhar-mani** [comment]
just write your own implementation if not possible then vibecode it

**Comment by RonRadtke** [comment]
@Ali-Aref  I am not able to reproduce it... neither in the test app nor in my production apps... 

get_constants is calling a native function, so for some reason the nativ function either returns a null or is never called.
So you would have to find out if it is calling the native logic or not and why not. E.g. if it is not build
