### ISSUE TITLE
[Android] NullPointerException in ReactNativeBlobUtilReq.cancelTask

### ISSUE THREAD

**Issue by jonthanon** [RonRadtke/react-native-blob-util#214]
We've been getting an occasional NullPointerException from `ReactNativeBlobUtilReq.cancelTask`:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void wn.e.cancel()' on a null object reference
        at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq.cancelTask(ReactNativeBlobUtilReq.java:152)
        at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq$3.onFailure(ReactNativeBlobUtilReq.java:475)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

My only guess, looking at the code for [cancelTask](https://github.com/RonRadtke/react-native-blob-util/blob/2e14e6b97bb6996306958a219fcb3e751732e16b/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java#L157), is that checking if the static `taskTable` contains a key before then fetching the results of that key might not be thread safe:
```
if (taskTable.containsKey(taskId)) {
    Call call = taskTable.get(taskId);
    call.cancel();
    taskTable.remove(taskId);
}
```

As far as I can tell, the only way to get the stack trace I'm getting is for `containsKey` to return true, but then `get` returns null. I can put up a PR to switch to just checking the `get` result.

_Full disclosure: We are on version 0.15.0 (and react-native 0.68.5), but this code hasn't changed in that time._

**Comment by RonRadtke** [comment]
hopefully fixed with the new version.
