### ISSUE TITLE
Android: app crashes when calling task.cancel() with DownloadManager = true

### ISSUE THREAD

**Issue by eduardo-santos-tribia** [RonRadtke/react-native-blob-util#234]
Hi, I'm trying to implement the `cancel` option during the file download. It's working correctly on iOS and on Android emulators, but on my personal Android device (Xiaomi Mi A3 with Android 12) I'm getting this Java Exception that crashes the app even with try/catch block: 

```java
FATAL EXCEPTION: main

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=tribia.interaxo.project.app.debug (has extras) } in com.ReactNativeBlobUtil.ReactNativeBlobUtilReq@6eae604

FATAL EXCEPTION: main
Process: tribia.interaxo.project.app.debug, PID: 26989
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=tribia.interaxo.project.app.debug (has extras) } in com.ReactNativeBlobUtil.ReactNativeBlobUtilReq@6eae604
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
	at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq.onReceive(ReactNativeBlobUtilReq.java:897)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
	... 8 more

```

**This is my react-native-blob-util implementation:**
```typescript
const configOptions = ...defaultFetchBlobOptions,
    fileCache: true,
    indicator: true,
    overwrite: true,
    addAndroidDownloads: {
      useDownloadManager: true,
      notification: true,
      mediaScannable: true,
      path: path,
      title: contentName,
      description: contentDescription,
      mime: mimeType,
  },
}

const fetchBlobTaskRef = useRef<StatefulPromise<FetchBlobResponse>>()

const cancelFetch = () => {
    fetchBlobTaskRef?.current?.cancel()
}

const handleFetch = async () => {
  fetchBlobTaskRef.current = ReactNativeBlobUtil.config(
    configOptions,
  ).fetch('GET', url)

  fetchBlobTaskRef.current
    .progress((received, total) => {
      const currentProgress = received / total
      console.log({currentProgress})
    })
    .then(async res => {
      const resStatus = res && res.info ? res.info().status : 'Unknow'

      if (resStatus === ApiHttpStatusEnum.OK) {
        if (IS_ANDROID) {
          await handleAndroidDownload(res, contentName, mimeType)
        }
      } else {
        log(`Something went wrong downloading ${contentName}, status ${resStatus}`)
      }
    })
    .catch(error => {
      console.log(error)
    })
}

```

I was trying to understand where the Java exception is happening and it is when calling the `dm.remove(downloadManagerIdForTaskId);` function on the `ReactNativeBlobUtilReq.java` file:
![image](https://user-images.githubusercontent.com/113356915/225926908-978ab5ef-17d9-4c0c-9c8b-f496505879e0.png)

More info:
* `RN: 0.71.3`  
* `BlobUtil: ^0.17.2`
*  Device Xiaomi Mi A3 with Android 12

**Comment by ZaycevDmitriy** [comment]
In the new versions, the old bug has reappeared [#179 ](https://github.com/RonRadtke/react-native-blob-util/issues/179). I made a pull request for this bug [237](https://github.com/RonRadtke/react-native-blob-util/pull/237)
