### ISSUE TITLE
ReactNativeBlobUtil.fs.stat() silently failing and returning nothing on iOS

### ISSUE THREAD

**Issue by kimthompson** [RonRadtke/react-native-blob-util#295]
**react-native-blob-util**: 0.19.0
**react-native**: 0.69.12 (not New Architecture, not Expo)

Hello! I am having a lot of trouble getting any information to show up when I called `ReactNativeBlobUtil.fs.stat` on a URI from [React Native Image Picker](https://github.com/react-native-image-picker/react-native-image-picker). After struggling with this for a bit and looking through all the troubleshooting tips, I decided to see if it worked on Android. It did.

Here's the example code, complete with all my desperate `console.log`s.

```typescript
    const [imageSize, setImageSize] = useState<number | undefined>(undefined);

    {/* ...omitted... */}

    const scanPhoto = async () => {
        const photo = await launchImageLibrary({
          mediaType: 'photo',
          quality: 0.8,
        });

        if (photo.assets === undefined || photo.assets[0] === undefined) {
          // IRL we probably want to handle this in a way that doesn't suck. But for the demo page I'm too lazy.
          throw photo.errorMessage;
        }
        console.log('photo', photo.assets[0].uri as string);

        const decodedPath = decodeURIComponent(photo.assets[0].uri as string);
        console.log('decodedPath', decodedPath);

        let stats = await ReactNativeBlobUtil.fs.stat(decodedPath);
        console.log('stats', stats);
        setImageSize(stats.size);
    };
```

The `decodedPath` bit wasn't there originally and didn't seem to make a difference.

No error is thrown in the console. It prints out the 'photo' and 'decodedPath' debug statements, but then it never prints the "stats" out or changes the imageSize state. 

I eventually rearranged the `stat` call to hopefully print out some helpful error information:

```typescript
    ReactNativeBlobUtil.fs
      .stat(decodedPath)
      .then(stats => {
        console.log('stats', stats);
        setImageSize(stats.size);
      })
      .catch(err => {
        console.error(err);
      });
```

...and here's what I got:

```
Error: failed to stat path `file:///Users/kimtho/Library/Developer/CoreSimulator/Devices/987BB6D2-BF08-419E-89F4-BE467D42859F/data/Containers/Data/Application/C0915CC0-FBAA-4AA6-9E28-4CA2D9A083DD/tmp/3B8C7F15-4409-4C29-964C-D94157C92D74.jpg` because it does not exist or it is not a folder
    at fs.js:270:24
    at MessageQueue.__invokeCallback (MessageQueue.js:463:13)
    at MessageQueue.js:125:12
    at MessageQueue.__guard (MessageQueue.js:368:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:124:10)
    at RNDebuggerWorker.js:2:384123
```

A similar message occurs if I try it on a physical iOS device as well (an iPhone mini 12). On an Android simulator or device, this works fine.

Thanks for your help!

**Comment by andresmejia3** [comment]
Same thing with me and it's also returning false for `fs.exists()`, but I've confirmed the image is there by opening up the folder manually in finder

**Comment by SebastianSingle99** [comment]
https://github.com/RonRadtke/react-native-blob-util/blob/master/ios/ReactNativeBlobUtil/ReactNativeBlobUtil.mm#L524

This is the failing line:
`exist = [fm fileExistsAtPath:path isDirectory:&isDir];`

NSFileManager doesn't seem to work with file-urls like `file:///Users/...`. If you strip away `file://` from the `decocedPath` it works.

**Comment by RonRadtke** [comment]
I'll see if I can adjust the code to automatically strip the file:// part
