### ISSUE TITLE
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()

### ISSUE THREAD

**Issue by noway** [RonRadtke/react-native-blob-util#64]
**the version of installed library and RN project.**
i'm using master branch: https://github.com/RonRadtke/react-native-blob-util/commit/7f82a51bc7b9a55542dde98d741f5014f4446e29

The library crashes on Interceptor:
```
09-15 14:36:04.279  4490  5680 E AndroidRuntime: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq$2.intercept(ReactNativeBlobUtilReq.java:437)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-15 14:36:04.279  4490  5680 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:929)
```

Workaround is available here: https://github.com/square/okhttp/issues/4986#issuecomment-533135855 but i can't figure out how to apply it

react native info:
```
yarn run v1.22.10
$ /Users/ilia/mytours/mytours-rn/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 650.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /var/folders/85/2xpmzxms1tsgzr9nqnhszzfw0000gn/T/yarn--1631677580033-0.9245969333433577/node
    Yarn: 1.22.10 - /var/folders/85/2xpmzxms1tsgzr9nqnhszzfw0000gn/T/yarn--1631677580033-0.9245969333433577/yarn
    npm: 7.21.0 - /opt/homebrew/bin/npm
    Watchman: 2021.08.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/ilia/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /opt/homebrew/opt/openjdk@11/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.3 => 0.62.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 2.44s.
```

**Comment by ganmor** [comment]
https://github.com/beedeez/rn-fetch-blob/commit/ecb29548a25df978cb489d05fa81eed497546391

**Comment by RonRadtke** [comment]
@ganmor based on your changes you will always only try to close one last response, and differs a bit compared to the workaround.
I see if I can integrate the workaround in the lib-

**Comment by ganmor** [comment]
For the record, looking at the stack trace, the exception occurs here: com.ReactNativeBlobUtil.ReactNativeBlobUtilReq$2.intercept(ReactNativeBlobUtilReq.java:437)

We do not see it all the time so this seem to be consistent with an exception causing the problem.

I don't really understand what you mean by "one last response", the example fix is a retry interceptor in a loop. But maybe I don't understand the code enough
